<?php

namespace AppRestoBundle\Repository;

/**
 * WeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWeekAdmin()
    {
        $lastSunday = new \DateTime('last sunday');
        $lastSundayPlusForWeek = new \DateTime('last sunday');
        $lastSundayPlusForWeek->modify('+4 week');
        $qb = $this->createQueryBuilder('w');
        $qb->select('w')
            ->where('w.start_week > :start')
            ->andWhere('w.end_week <= :end')
            ->setParameters(
                array(
                    'start' => $lastSunday,
                    'end' => $lastSundayPlusForWeek
                )
            );
        return $qb->getQuery()->getResult();
    }
}
