app_resto_meal:
    resource: "@AppRestoBundle/Resources/config/routing/meal.yml"
    prefix:   /meal

app_resto_week:
    resource: "@AppRestoBundle/Resources/config/routing/week.yml"
    prefix:   /week

app_resto_day:
    resource: "@AppRestoBundle/Resources/config/routing/day.yml"
    prefix:   /day

app_resto_comment:
    resource: "@AppRestoBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

app_resto_follower:
    resource: "@AppRestoBundle/Resources/config/routing/follower.yml"
    prefix:   /follower

app_resto_admin_routing:
    resource: "@AppRestoBundle/Resources/config/routing/admin/admin_routing.yml"
    prefix:   /admin

app_resto_homepage:
    path:     /
    defaults: { _controller: AppRestoBundle:Client:client}

app_resto_admin:
    path:     /admin
    defaults: { _controller: AppRestoBundle:Admin:admin}

app_resto_admin_counter:
    path:     /admin/counter
    defaults: { _controller: AppRestoBundle:Admin:counter}

app_resto_com_valid:
    path: /admin/counter/{id}/valid
    defaults: { _controller: AppRestoBundle:Admin:valid}
    methods: GET

app_resto_com_archiv:
    path: /admin/counter/{id}/archiv
    defaults: { _controller: AppRestoBundle:Admin:archiv}
    methods: GET

app_resto_send:
    path:     /send
    defaults: { _controller: AppRestoBundle:Admin:send}

app_resto_mail:
    path:     /mail
    defaults: { _controller: AppRestoBundle:Admin:mail}
