app_resto_meal:
    resource: "@AppRestoBundle/Resources/config/routing/meal.yml"
    prefix:   /meal

app_resto_week:
    resource: "@AppRestoBundle/Resources/config/routing/week.yml"
    prefix:   /week

app_resto_day:
    resource: "@AppRestoBundle/Resources/config/routing/day.yml"
    prefix:   /day

app_resto_comment:
    resource: "@AppRestoBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

app_resto_follower:
    resource: "@AppRestoBundle/Resources/config/routing/follower.yml"
    prefix:   /follower

app_resto_homepage:
    path:     /
    defaults: { _controller: AppRestoBundle:Client:client}

app_resto_admin:
    path:     /admin
    defaults: { _controller: AppRestoBundle:Admin:admin}

app_resto_admin_counter:
    path:     /admin/counter
    defaults: { _controller: AppRestoBundle:Admin:counter}

