app_resto_comment:
    resource: "@AppRestoBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

app_resto_admin:
    resource: "@AppRestoBundle/Resources/config/routing/admin/admin_routing.yml"
    prefix:   /admin



app_resto_homepage:
    path:     /
    defaults: { _controller: AppRestoBundle:Client:client}
    methods: [GET, POST]

app_resto_admin_counter:
    path:     /admin/counter
    defaults: { _controller: AppRestoBundle:Admin:counter}

app_resto_com_valid:
    path:     /admin/counter/{id}/valid
    defaults: { _controller: AppRestoBundle:Admin:valid}
    methods: GET

app_resto_com_archiv:
    path:     /admin/counter/{id}/archiv
    defaults: { _controller: AppRestoBundle:Admin:archiv}
    methods: GET

app_resto_send:
    path:     /send
    defaults: { _controller: AppRestoBundle:Admin:send}

app_resto_mail:
    path:     /mail
    defaults: { _controller: AppRestoBundle:Admin:mail}

app_resto_add_mail:
    path:     /add_mail
    defaults: { _controller: AppRestoBundle:Follower:add}

app_resto_add_resa:
    path:     /add_resa
    defaults: { _controller: AppRestoBundle:Client:resa}
    methods: ['GET', 'POST']


