app_resto_admin:
    resource: "@AppRestoBundle/Resources/config/routing/admin/admin_routing.yml"
    prefix:   /admin

app_resto_homepage:
    path:     /
    defaults: { _controller: AppRestoBundle:Client:client}
    methods:  [GET, POST]

app_resto_add_mail:
    path:     /add_mail
    defaults: { _controller: AppRestoBundle:Follower:add}

app_resto_add_resa:
    path:     /add_resa
    defaults: { _controller: AppRestoBundle:Client:resa}
    methods: ['GET', 'POST']