app_resto_load_week_ajax:
    path:     /
    defaults: { _controller: AppRestoBundle:Admin:loadWeekAjax}

app_resto_entree_ajax:
    path:     /entree
    defaults: { _controller: AppRestoBundle:Admin:addEntree}

app_resto_plat_ajax:
    path:     /plat
    defaults: { _controller: AppRestoBundle:Admin:addPlat}

app_resto_garniture_ajax:
    path:     /garniture
    defaults: { _controller: AppRestoBundle:Admin:addGarniture}

app_resto_dessert_ajax:
    path:     /dessert
    defaults: { _controller: AppRestoBundle:Admin:addDessert}

app_resto_admin_counter:
    path:     /counter
    defaults: { _controller: AppRestoBundle:Admin:counter}

app_resto_com_valid:
    path:     /counter/{id}/valid
    defaults: { _controller: AppRestoBundle:Admin:valid}
    methods: GET

app_resto_com_archiv:
    path:     /counter/{id}/archiv
    defaults: { _controller: AppRestoBundle:Admin:archiv}
    methods: GET

app_resto_admin_send:
    path:     /send
    defaults: { _controller: AppRestoBundle:Admin:send}

app_resto_mail:
    path:     /mail
    defaults: { _controller: AppRestoBundle:Admin:mail}

app_resto_meal:
    path: /meal
    defaults: {_controller: AppRestoBundle:Meal:meal}

app_resto_entree_delete:
    path:     /meal/entree/{id}/delete
    defaults: { _controller: AppRestoBundle:Meal:deleteEntree}
    methods: GET

app_resto_plat_delete:
    path:     /meal/plat/{id}/delete
    defaults: { _controller: AppRestoBundle:Meal:deletePlat}
    methods: GET

app_resto_garniture_delete:
    path:     /meal/garniture/{id}/delete
    defaults: { _controller: AppRestoBundle:Meal:deleteGarniture}
    methods: GET

app_resto_dessert_delete:
    path:     /meal/dessert/{id}/delete
    defaults: { _controller: AppRestoBundle:Meal:deleteDessert}
    methods: GET
