follower_index:
    path:     /
    defaults: { _controller: "AppRestoBundle:Follower:index" }
    methods:  GET

follower_show:
    path:     /{id}/show
    defaults: { _controller: "AppRestoBundle:Follower:show" }
    methods:  GET

follower_new:
    path:     /new
    defaults: { _controller: "AppRestoBundle:Follower:new" }
    methods:  [GET, POST]

follower_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppRestoBundle:Follower:edit" }
    methods:  [GET, POST]

follower_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppRestoBundle:Follower:delete" }
    methods:  DELETE
