type_index:
    path:     /
    defaults: { _controller: "AppRestoBundle:Type:index" }
    methods:  GET

type_show:
    path:     /{id}/show
    defaults: { _controller: "AppRestoBundle:Type:show" }
    methods:  GET

type_new:
    path:     /new
    defaults: { _controller: "AppRestoBundle:Type:new" }
    methods:  [GET, POST]

type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppRestoBundle:Type:edit" }
    methods:  [GET, POST]

type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppRestoBundle:Type:delete" }
    methods:  DELETE
