week_index:
    path:     /
    defaults: { _controller: "AppRestoBundle:Week:index" }
    methods:  GET

week_show:
    path:     /{id}/show
    defaults: { _controller: "AppRestoBundle:Week:show" }
    methods:  GET

week_new:
    path:     /new
    defaults: { _controller: "AppRestoBundle:Week:new" }
    methods:  [GET, POST]

week_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppRestoBundle:Week:edit" }
    methods:  [GET, POST]

week_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppRestoBundle:Week:delete" }
    methods:  DELETE
