AppRestoBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppRestoBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        author:
            type: string
            length: 255
        date:
            type: datetime
        valid:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
