AppRestoBundle\Entity\Day:
    type: entity
    table: null
    repositoryClass: AppRestoBundle\Repository\DayRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime

    manyToMany:
        entrees:
            targetEntity: AppRestoBundle\Entity\Entree

        plats:
            targetEntity: AppRestoBundle\Entity\Plat

        desserts:
            targetEntity: AppRestoBundle\Entity\Dessert

        garnitures:
            targetEntity: AppRestoBundle\Entity\Garniture

    oneToOne:
        resas:
            targetEntity: AppRestoBundle\Entity\Resa
            cascade: ['persist']
