AppRestoBundle\Entity\Day:
    type: entity
    table: null
    repositoryClass: AppRestoBundle\Repository\DayRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime

    manyToMany:
        meal:
            targetEntity: AppRestoBundle\Entity\Meal

        type:
            targetEntity: AppRestoBundle\Entity\Type
