AppRestoBundle\Entity\Week:
    type: entity
    table: null
    repositoryClass: AppRestoBundle\Repository\WeekRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nbWeek:
            type: integer
            column: nb_week
        message:
            type: text
            nullable: true

    oneToMany:
        day:
            targetEntity: AppRestoBundle\Entity\Day
            mappedBy: week