AppRestoBundle\Entity\Week:
    type: entity
    table: null
    repositoryClass: AppRestoBundle\Repository\WeekRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start_week:
            type: datetime

        end_week:
            type: datetime

        message:
            type: text
            nullable: true

    manyToMany:
        days:
            targetEntity: AppRestoBundle\Entity\Day
            joinTable:
                name: Week_Day